---

- name: Make instances of OpenVPN
  become: yes
  template:
    src: "{{ openvpn_sysDunit[0] }}.j2"
    dest: "/{{ openvpn_sysDunit[0] }}"
    owner: root
    group: root
    mode: 0644
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN server configuration file
  become: yes
  template:
    src: "{{ openvpn_sysDunit[1] }}.j2"
    dest: "/{{ openvpn_sysDunit[1] }}"
    owner: root
    group: root
    mode: 0640
  when: openvpn_server
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN client configuration file
  become: yes
  template:
    src: "{{ openvpn_sysDunit[2] }}.j2"
    dest: "/{{ openvpn_sysDunit[2] }}"
    owner: root
    group: root
    mode: 0640
  when: openvpn_client
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN static key
  become: yes
  template:
    src: "{{ openvpn_sysDunit[3] }}.j2"
    dest: "/{{ openvpn_sysDunit[3] }}"
    owner: root
    group: root
    mode: 0600
  when: openvpn_static
  notify: restart openvpn
  tags:
    - config

...
