---

- name: Make instances of OpenVPN
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "etc/systemd/system/openvpn@.service"
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN static key
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "etc/openvpn/{{ openvpn_secretfile }}"
  when: openvpn_static
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN tls-auth key
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - "etc/openvpn/{{ openvpn_tafile }}"
  when: openvpn_tlsauth
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN server configuration file
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "etc/openvpn/server.conf"
  when: openvpn_server
  notify: restart openvpn
  tags:
    - config

- name: Create OpenVPN client configuration file
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "etc/openvpn/client.conf"
  when: openvpn_client
  notify: restart openvpn
  tags:
    - config

...
