---
#
#- name: Install OpenVPN GPG key
#  become: yes
#  apt_key:
#    url: "{{ openvpn_deburl }}/pubkey.gpg"
#    state: present
#  tags:
#    - install

#- name: Add OpenVPN repository
#  become: yes
#  apt_repository:
#    repo: 'deb {{ openvpn_deburl }} {{ ansible_distribution_release }} main'
#    state: present
#  tags:
#    - install

- name: Install OpenVPN packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ openvpn_packages }}"
  tags:
    - install
