---
#

- name: Create OpenVPN defaults configuration file
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "etc/default/openvpn"
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - config

- name: Fix Xenial systemd service unit file
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "etc/systemd/system/openvpn@.service"
  when: ansible_distribution_release == "xenial"
  notify:
    - reload systemd
  tags:
    - config
