---
#
# Main playbook of OpenVPN role
#

# OpenVPN. Server's side.
- hosts: server
  gather_facts: false
  become: yes
  roles:
    - { role: openvpn, openvpn_server: true, openvpn_static: true }

# OpenVPN. Client's side.
- hosts: client
  gather_facts: false
  become: yes
  roles:
    - { role: openvpn, openvpn_client: true, openvpn_remotehost: '192.168.10.100', openvpn_static: true }

