---

- hosts: masters etcd nodes
  become: yes
#  roles:
#    - { role: CentOS_Srv }




# Servers of logs
#- hosts: logsrv 
#  become: yes
#  roles:
#    - { role: ntpd }
#    - { role: journaldSrv }
#    - { role: rsyslogSrv }

# Servers of ELK stack
#- hosts: logweb
#  become: yes
#  roles:
#    - { role: ELK }

# Web server
#- hosts: web01
#  become: yes
#  roles:
#    - { role: nginx }
#    - { role: journaldClient }
#    - { role: rsyslogClient }

