filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/nginx/access.log*
    - /var/log/nginx/error.log*
  exclude_files: [".gz$"]
  multiline:
    pattern: "^\\s"
    match: after
output.logstash:
  hosts: ["192.168.168.110:5044"]
