---
#
# OpenVPN client side
#
- hosts: server
  become: yes
  roles:
    - { role: openvpn, openvpn_server: true, openvpn_static: false }

- hosts: buh1
  become: yes
  roles:
    - { role: openvpn, openvpn_client: true, openvpn_remotehost: '192.168.10.100', openvpn_remoteport: '1194', openvpn_static: false }

