---

openvpn_secretfile: static.key
openvpn_tafile: ta.key
openvpn_group: nogroup
openvpn_packages: openvpn={{ openvpn_version }}*
openvpn_servicename: openvpn
openvpn_user: nobody
openvpn_list: install

...
